ros_impedance_controller:
  type: ros_impedance_controller/Controller
  joints:
    - lf_haa_joint
    - lf_hfe_joint
    - lf_kfe_joint
    - rf_haa_joint
    - rf_hfe_joint
    - rf_kfe_joint
    - lh_haa_joint
    - lh_hfe_joint
    - lh_kfe_joint
    - rh_haa_joint
    - rh_hfe_joint
    - rh_kfe_joint
  gains:
    lf_haa_joint: {p: 5.00, i: 0.0, d: 0.1}
    lf_hfe_joint: {p: 5.00, i: 0.0, d: 0.1}
    lf_kfe_joint: {p: 5.00, i: 0.0, d: 0.1}

    rf_haa_joint: {p: 5.00, i: 0.0, d: 0.1}
    rf_hfe_joint: {p: 5.00, i: 0.0, d: 0.1}
    rf_kfe_joint: {p: 5.00, i: 0.0, d: 0.1}

    lh_haa_joint: {p: 5.00, i: 0.0, d: 0.1}
    lh_hfe_joint: {p: 5.00, i: 0.0, d: 0.1}
    lh_kfe_joint: {p: 5.00, i: 0.0, d: 0.1}

    rh_haa_joint: {p: 5.00, i: 0.0, d: 0.1}
    rh_hfe_joint: {p: 5.00, i: 0.0, d: 0.1}
    rh_kfe_joint: {p: 5.00, i: 0.0, d: 0.1}

  home:
    lf_haa_joint:  0.6
    lf_hfe_joint:  1.7
    lf_kfe_joint: 3.7
    
    rf_haa_joint:  -0.6
    rf_hfe_joint:  1.7
    rf_kfe_joint: 3.7
    
    lh_haa_joint:  0.6
    lh_hfe_joint:  1.7
    lh_kfe_joint: 3.7
    
    rh_haa_joint: -0.6
    rh_hfe_joint:  1.7
    rh_kfe_joint: 3.7
   
